### ISSUE TITLE
'invalid argument'

### ISSUE THREAD

**Issue by jsnanavati** [k3ai/k3ai#47]
Hello - I am trying out the Mlflow deployment as in the tutorials and I get a stream of logs that say "invalid argument" and after a while I get "We tried to publish MLFLow at:http://172.17.0.2:30500" .. but when I go to this page there is no Mlflow server.

Would appreciate the help. Thanks.

Great work btw! this library is amazing!

**Comment by alefesta** [comment]
Hi @jsnanavati  I'm investigating this.. could you give me more info on your error?:
1) what type of cluster you are trying to install? From your IP seems like KiNd or k3d?
If so that's the problem similar to #24 that I'm trying to solve.. there's no easy way at the moment if not using a port-forward..I'll update the docs in the coming weeks for this.
